-- 코드를 입력하세요
# SELECT *
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS AS INS
INNER JOIN ANIMAL_OUTS AS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
AND INS.SEX_UPON_INTAKE LIKE "%Intact%"
AND (OUTS.SEX_UPON_OUTCOME LIKE "%Neutered%" 
     OR OUTS.SEX_UPON_OUTCOME LIKE "%Spayed%")
ORDER BY INS.ANIMAL_ID