-- 코드를 입력하세요
SELECT USER.USER_ID, USER.NICKNAME, SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS USER ON BOARD.WRITER_ID=USER.USER_ID
WHERE BOARD.STATUS in ("DONE")
GROUP BY BOARD.WRITER_ID
HAVING TOTAL_PRICE >= 70*10000
ORDER BY TOTAL_PRICE;
