-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID=A.AUTHOR_ID
JOIN BOOK_SALES AS S ON S.BOOK_ID=B.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") LIKE "%22-01%"
GROUP BY B.CATEGORY, B.AUTHOR_ID     # 이거 세개가 같아야 하나의 ROW
# HAVING DATE_FORMAT(S.SALES_DATE, "%Y-%m") = "2022-01"
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
